First ten generated NFT should be free
Haykmnatsakanyan/blockchain-truffle pull request #1
Opened 2022-04-13 07:55 UTC by Haykmnatsakanyan

Added functionality for generating first 10 NFT's for free afterwards it will become 0,01 Ethereum for each NFT.

2022-04-13 15:17 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
>          require(msg.value >= cost, "Less than price");
If user will pass more than cost accidentally we are not preventing it. 
What solutions do we have in that case if `msg.value == cost` is not the correct way?

2022-04-15 19:09 UTC, edvardg commented on contracts/UniqueAsset.sol
>  import "@openzeppelin/contracts/utils/Counters.sol";
I think this line can be removed as `Counters` contract is not used

2022-04-15 19:12 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    event Minted(address owner);
I think this event is redundant. mint() function emits `Transfer` event according to OpenZeppelin implementation:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L289

2022-04-15 19:13 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    uint256 public TokenPrice = 1e16;
let's use lowercase state variables (`tokenPrice` instead of `TokenPrice`)

2022-04-15 19:15 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    mapping(address => uint8) private freeMintingAmountPerUser;
private state variables usually start with _, i.e. `_freeMintingAmountPerUser` instead of `freeMintingAmountPerUser`.
The same for `baseURI` - you can use _<someVariableName>

2022-04-15 19:19 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    function mint(address payable sender) external payable validAddress {
I'd suggest to add `nonReentrant` modifier for this function to prevent possible issues when the same address makes multiple calls at the same time.
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/ReentrancyGuard.sol#L50

2022-04-15 19:22 UTC, edvardg commented on contracts/UniqueAsset.sol
> +        _safeMint(sender, totalSupply() + 1);
I think it is redundant to have `sender` argument - you can use `msg.sender` instead.

2022-04-15 19:26 UTC, edvardg requested changes

2022-04-15 19:26 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    function mint(address payable sender) external payable validAddress {
Also, it's not super critical to have an additional `validAddress` modifier - `_mint()` function does already such validation, so no need to increase contract size) 
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L281

2022-04-15 19:26 UTC, edvardg commented on contracts/UniqueAsset.sol
> +        return baseURI;
let's rename the private variable and have something like: `_tokenBaseURI` instead of `baseURI`

2022-04-15 19:28 UTC, edvardg commented on contracts/UniqueAsset.sol
>          require(msg.value >= cost, "Less than price");
sometime you can get incorrect value in `msg.value`. f.e. you can get `0.010000000011` instead of `0.01`. That's why we use to use `msg.value >=<someValue>` instead of ==

2022-04-16 06:35 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
>          require(msg.value >= cost, "Less than price");
I remember it, but user can accidentally pass 10 times more WEI and we are not preventing it, right?
I believe we should take care such kind of cases as well 🧐

2022-04-16 06:36 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
>  import "@openzeppelin/contracts/utils/Counters.sol";
Correct, thanks

2022-04-16 06:37 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
> +    event Minted(address owner);
Good catch :)

2022-04-16 06:41 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
> +    mapping(address => uint8) private freeMintingAmountPerUser;
Interesting, in the github of OpenZepplin they write state variables without `_` instead of that they write function arguments with the same name but with `_`. Maybe your suggestion more general practice? Just would like to make sure before changing.

2022-04-16 06:45 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
> +    function mint(address payable sender) external payable validAddress {
> 

Concerning nonReentrant it is perfect suggestion just would like to investigate that topic today )))

2022-04-16 06:45 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
> +    function mint(address payable sender) external payable validAddress {
> size

Good to know, thanks

2022-04-16 20:35 UTC, edvardg commented on contracts/UniqueAsset.sol
>          require(msg.value >= cost, "Less than price");
Good point, but thats user responsibility to specify correct value in a message. At the end products usually have a user interface where correct value is specified.

2022-04-16 20:37 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    uint256 public _tokenPrice = 1e16;
minor comment - public variables do not need _, so makes sense to have `tokenPrice` instead of `_tokenPrice`

2022-04-16 20:47 UTC, edvardg commented on contracts/UniqueAsset.sol
> +    mapping(address => uint8) private freeMintingAmountPerUser;
hmm, I think it depends which contract did you check. For example here they use the same practice:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/extensions/ERC721URIStorage.sol#L15

The best practice is:
- use camelCase for public state variables (for example `tokenPrice`)
- use _camelCase for non-public state variables (for example `_tokenPrice`)
- use one of the following patterns for function arguments: _camelCase, camelCase or camelCase_ (not super critical for function arguments).

2022-04-16 20:47 UTC, edvardg approved these changes

2022-04-17 06:44 UTC, Haykmnatsakanyan commented on contracts/UniqueAsset.sol
> +    mapping(address => uint8) private freeMintingAmountPerUser;
Got it, thanks

2022-04-17 07:51 UTC, merged